// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int deadNormalCar2_2c18d2378a4f5614e93b2558d9c45d42Index = 0;
		public const int MultiplayerCar_fde46f4435c0d0c4f9f3326aa9feca8eIndex = 1;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "deadNormalCar2_2c18d2378a4f5614e93b2558d9c45d42", 0 },

			{ "MultiplayerCar_fde46f4435c0d0c4f9f3326aa9feca8e", 1 },

		};
	}
}
