// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct MultiplayerCar_onlineName_6379893805495976556 : ICoherenceComponentData
	{
		public SerializeEntityID nameTagPrefab;
		public string playerName;

		public override string ToString()
		{
			return $"MultiplayerCar_onlineName_6379893805495976556(nameTagPrefab: {nameTagPrefab}, playerName: {playerName})";
		}

		public uint GetComponentType() => Definition.InternalMultiplayerCar_onlineName_6379893805495976556;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (MultiplayerCar_onlineName_6379893805495976556)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				nameTagPrefab = other.nameTagPrefab;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				playerName = other.playerName;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static void Serialize(MultiplayerCar_onlineName_6379893805495976556 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteEntity(data.nameTagPrefab);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteShortString(data.playerName);
			}
			mask >>= 1;
		}

		public static (MultiplayerCar_onlineName_6379893805495976556, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new MultiplayerCar_onlineName_6379893805495976556();
	
			if (bitStream.ReadMask())
			{
				val.nameTagPrefab = bitStream.ReadEntity();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.playerName = bitStream.ReadShortString();
				mask |= 0b00000000000000000000000000000010;
			}
			return (val, mask, null);
		}
		public static (MultiplayerCar_onlineName_6379893805495976556, uint, uint?) DeserializeArchetypeMultiplayerCar_fde46f4435c0d0c4f9f3326aa9feca8e_MultiplayerCar_onlineName_6379893805495976556_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new MultiplayerCar_onlineName_6379893805495976556();
			if (bitStream.ReadMask())
			{
				val.nameTagPrefab = bitStream.ReadEntity();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.playerName = bitStream.ReadShortString();
				mask |= 0b00000000000000000000000000000010;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as MultiplayerCar_onlineName_6379893805495976556?;
	
		}
	}
}